name: Evolution Athletics
favicon: null
layout_spectrum: 0.2429
typography_spectrum: 0.64284
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0d0f'
    - '#ffffff'
    - '#48494c'
    - '#acb3b7'
    - '#d81f26'
  brandStrength: 0.9102921590674669
  lightness: 0.3190553062595427
  saturation: 0.6501775276847184
  rhythmicContrast: 0.7791150817647576
purpose: []
